### ISSUE TITLE
Diff styling for the demo

### ISSUE THREAD

**Issue by maliayas** [caxy/php-htmldiff#45]
I suggest adding a red/green styling for the demo diffs. Below is a fancy one:

````css
ins {
    color: #333333;
    background-color: #eaffea;

    text-decoration: none;
}
del {
    color: #AA3333;
    background-color: #ffeaea;

    text-decoration: line-through;
}
````
